// Command genexercises regenerates pkg/garmin/exercises_gen.go from Garmin
// Connect's public exercise taxonomy (the file the Connect web app itself
// loads). Run from the repository root:
//
//	go run ./internal/genexercises
package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"sort"
	"strings"
)

const taxonomyURL = "https://connect.garmin.com/web-data/exercises/Exercises.json"

func main() {
	resp, err := http.Get(taxonomyURL)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		panic(fmt.Sprintf("GET %s: %s", taxonomyURL, resp.Status))
	}
	var doc struct {
		Categories map[string]struct {
			Exercises map[string]struct {
				PrimaryMuscles []string `json:"primaryMuscles"`
			} `json:"exercises"`
		} `json:"categories"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&doc); err != nil {
		panic(err)
	}

	cats := make([]string, 0, len(doc.Categories))
	for c := range doc.Categories {
		cats = append(cats, c)
	}
	sort.Strings(cats)

	var b strings.Builder
	b.WriteString("// Code generated by go run ./internal/genexercises; DO NOT EDIT.\n")
	b.WriteString("// Source: " + taxonomyURL + "\n\npackage garmin\n\n")
	b.WriteString("// Exercise categories of the Garmin Connect strength taxonomy.\nconst (\n")
	for _, c := range cats {
		fmt.Fprintf(&b, "\tExerciseCategory%s = %q\n", camel(c), c)
	}
	b.WriteString(")\n\n")
	b.WriteString("// exerciseCategoryOrder lists the categories in sorted order.\nvar exerciseCategoryOrder = []string{\n")
	for _, c := range cats {
		fmt.Fprintf(&b, "\t%q,\n", c)
	}
	b.WriteString("}\n\n")
	b.WriteString("// exercisesByCategory maps each category to its exercise names.\nvar exercisesByCategory = map[string][]string{\n")
	total := 0
	for _, c := range cats {
		names := make([]string, 0, len(doc.Categories[c].Exercises))
		for n := range doc.Categories[c].Exercises {
			names = append(names, n)
		}
		sort.Strings(names)
		total += len(names)
		fmt.Fprintf(&b, "\t%q: {\n", c)
		for _, n := range names {
			fmt.Fprintf(&b, "\t\t%q,\n", n)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	fmt.Fprintf(os.Stderr, "generated %d categories, %d exercises\n", len(cats), total)
	if err := os.WriteFile("pkg/garmin/exercises_gen.go", []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
}

// camel turns SNAKE_UPPER into CamelCase for a Go identifier.
func camel(s string) string {
	parts := strings.Split(strings.ToLower(s), "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}
